Repository n-ce/ytify, pull requests merged in 2025-01, with the labels that each got.

#241 7.6
  index.html
  netlify/edge-functions/listPreview.ts
  package.json
  src/components/ActionsMenu.tsx
  src/components/Lyrics.tsx
  src/components/Settings.tsx
  src/components/UpdatePrompt.tsx
  src/components/WatchOnYtify.tsx
  src/index.d.ts
  src/lib/dom.ts
  src/lib/libraryUtils.ts
  src/lib/store.ts
  src/lib/utils.ts
  src/modules/getStreamData.ts
  src/modules/hls.ts
  src/modules/partsManager.ts
  src/modules/setAudioStreams.ts
  src/modules/start.ts
  src/modules/supermix.ts
  src/scripts/audioEvents.ts
  src/scripts/list.ts
  src/scripts/queue.ts
  src/scripts/router.ts
  src/stylesheets/global.css
  src/stylesheets/list.css
  src/stylesheets/miniPlayer.css
Labels: enhancement

#252 Implement Translations
  .gitignore
  index.html
  lingui.config.ts
  package.json
  src/components/ActionsMenu.tsx
  src/components/CollectionSelector.tsx
  src/components/Settings.tsx
  src/components/UpdatePrompt.tsx
  src/locales/en.ts
  src/locales/pl.ts
  src/main.ts
  src/modules/fetchList.ts
  src/modules/importPipedPlaylists.ts
  src/modules/listUtils.ts
  src/modules/miniPlayer.ts
  src/modules/partsManager.ts
  src/modules/setAudioStreams.ts
  src/modules/start.ts
  src/scripts/i18n.ts
Labels: enhancement, Javascript

#258 7.7
  .gitignore
  README.md
  index.html
  netlify/edge-functions/blobs.ts
  netlify/edge-functions/getCollection.ts
  netlify/edge-functions/getStreamData.ts
  netlify/edge-functions/landing.ts
  netlify/edge-functions/linkPreview.ts
  package.json
  public/remixicon.woff2
  src/components/ActionsMenu.tsx
  src/components/CollectionSelector.tsx
  src/components/ListItem.tsx
  src/components/Lyrics.tsx
  src/components/Settings.tsx
  src/components/StreamItem.tsx
  src/components/UpdatePrompt.tsx
  src/components/WatchOnYtify.tsx
  src/imsc.d.ts
  src/index.d.ts
  src/lib/dom.ts
  src/lib/libraryUtils.ts
  src/lib/player.ts
  src/lib/store.ts
  src/lib/utils.ts
  src/locales/en.json
  src/locales/hi.json
  src/locales/pl.json
  src/locales/sa.json
  src/main.ts
  src/modules/fetchList.ts
  src/modules/getStreamData.ts
  src/modules/hls.ts
  src/modules/importPipedPlaylists.ts
  src/modules/listUtils.ts
  src/modules/miniPlayer.ts
  src/modules/partsManager.ts
  src/modules/setAudioStreams.ts
  src/modules/setMetadata.ts
  src/modules/setSubtitles.ts
  src/modules/start.ts
  src/modules/supermix.ts
  src/scripts/audioEvents.ts
  src/scripts/i18n.ts
  src/scripts/library.ts
  src/scripts/list.ts
  src/scripts/queue.ts
  src/scripts/router.ts
  src/scripts/search.ts
  src/scripts/theme.ts
  src/stylesheets/global.css
  src/stylesheets/home.css
  src/stylesheets/library.css
  src/stylesheets/list.css
  src/stylesheets/remixicon.css
  vite.config.ts
Labels: enhancement, UI / UX, Translations
